//@version=5
strategy("布林帶交叉策略", overlay=true,default_qty_type=strategy.percent_of_equity, default_qty_value=100)

length = input.int(20, minval=1, title="BB Length")
mult = input.float(2.0, minval=0.1, maxval=5.0, title="BB StdDev")
basis = ta.sma(close, length)
dev = mult * ta.stdev(close, length)
upper = basis + dev
lower = basis - dev

longSignal = ta.crossunder(close, lower)

if (longSignal)
    strategy.entry("Long Entry", strategy.long)


shortSignal = ta.crossover(close, upper)
shortLoss = strategy.position_avg_price +10
shortProfit = strategy.position_avg_price * 0.95

if (shortSignal)
    strategy.entry("Short Entry", strategy.short)

if (strategy.position_size < 0)
    strategy.exit("Short Exit", "Short Entry", stop=shortLoss, limit=shortProfit)
